meta:
    site_title: "刘飞宇的文艺博客"
    site_subtitle: "人生就是要不停的奋斗"
    site_language: "zh-cn"
    absolute_baseurl: http://life.liufeiyu.cn
    domain: liufeiyu.cn
    author:
        full_name:Liu Feiyu
        short_name: feiyuliu
        name: feiyuliu
        email: liufeiyu323@gmail.com

url: http://life.liufeiyu.cn

#baseurl: /base

markdown: kramdown

# markdown: maruku
# maruku:
#   use_divs: true
#    use_tex: true
#    png_engine : blahtex
#    png_dir    : images/latex/
#    png_url    : /images/latex/

pygments: false
permalink: /blog/:year/:month/:day/:title

disqus_short_name: ypchenstory

      
css:
    - /css/screen.css


