meta:
    site_title: "刘飞宇的生活博客"
    site_subtitle: "人生就是要不停的奋斗"
    site_language: "zh-cn"
    absolute_baseurl: http://liufeiyu.cn/life/
    domain: liufeiyu.cn
    author:
        full_name:Liu Feiyu
        short_name: feiyuliu
        name: feiyuliu
        email: liufeiyu323@gmail.com

url: http://liufeiyu.cn/life/

baseurl: /life

markdown: kramdown

# markdown: maruku
# maruku:
#   use_divs: true
#    use_tex: true
#    png_engine : blahtex
#    png_dir    : images/latex/
#    png_url    : /images/latex/

pygments: false
permalink: /:year/:month/:day/:title

disqus_short_name: lifeliufeyu

      
css:
    - /css/screen.css


